import { initAuthPages, initRouteGuards } from "./auth.js";
import { initDashboardPage } from "./dashboard.js";
import { initGroupsPage } from "./groups.js";
import { initContributionsPage } from "./contributions.js";
import { initPaymentsPage } from "./payments.js";
import { initQrPage } from "./qr.js";
import { initProfilePage } from "./profile.js";
import { initSettingsPage } from "./settings.js";
import { bindThemeButtons, applySavedTheme } from "./theme.js";
import { bindOfflineBanner } from "./ui.js";
import { initAppNavigation, initLandingLinks, initPublicNavigation, initRoleSwitcher } from "./navigation.js";

document.addEventListener("DOMContentLoaded", async () => {
  applySavedTheme();
  const canContinue = initRouteGuards();
  if (!canContinue) return;
  initPublicNavigation();
  initAppNavigation();
  initLandingLinks();
  initRoleSwitcher();
  bindThemeButtons();
  bindOfflineBanner();
  initAuthPages();
  await initDashboardPage();
  await initGroupsPage();
  await initContributionsPage();
  await initPaymentsPage();
  await initQrPage();
  await initProfilePage();
  initSettingsPage();
});
